name: Hourly Amazon Price Scraper

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:      

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run scraper
        run: python amazon_scraper.py
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
